### ISSUE TITLE
Unable to clone Memtest86+ from Git

### ISSUE THREAD

**Issue by Strongbyte-SD** [pcengines/pce-fw-builder#48]
I run in to the following error when building a new release version. 

Steps 

1.     `git clone https://github.com/pcengines/pce-fw-builder.git -b 1.52.5`
2.      `cd pce-fw-builder`
3.     `./build.sh release v4.14.0.4 apu2`

Results in the following error. 

```  Compile checking out/src/fw/xen.o
  Compile checking out/src/fw/acpi.o
  Compile checking out/src/fw/mptable.o
  Compile checking out/src/fw/pirtable.o
  Compile checking out/src/fw/smbios.o
  Compile checking out/src/fw/romfile_loader.o
  Compile checking out/src/fw/dsdt_parser.o
  Compile checking out/src/fw/vpd.o
  Compile checking out/src/fw/lib_vpd.o
  Compile checking out/src/hw/virtio-ring.o
  Compile checking out/src/hw/virtio-pci.o
  Compile checking out/src/hw/virtio-mmio.o
  Compile checking out/src/hw/virtio-blk.o
  Compile checking out/src/hw/virtio-scsi.o
  Compile checking out/src/hw/tpm_drivers.o
  Compile checking out/src/hw/nvme.o
  Compiling whole program out/ccode32flat.o
  Compiling whole program out/code32seg.o
  Compiling whole program out/ccode16.o
  Compiling to assembler out/src/asm-offsets.s
  Generating offset file out/asm-offsets.h
  Compiling (16bit) out/romlayout.o
  Building ld scripts
Version: rel-1.14.0.1-0-g8610266a
Fixed space: 0xe05b-0x10000  total: 8101  slack: 3  Percent slack: 0.0%
16bit size:           26688
32bit segmented size: 1292
32bit flat size:      21700
32bit flat init size: 36896
Lowmem size:          2240
f-segment var size:   1392
  Linking out/rom16.o
  Stripping out/rom16.noexec.o
  Linking out/rom32seg.o
  Stripping out/rom32seg.noexec.o
  Linking out/rom.o
  Prepping out/bios.bin.prep
Total size: 92384  Fixed: 51072  Free: 38688 (used 70.5% of 128KiB rom)
  Creating out/bios.bin.elf
    Cloning Memtest86+ from Git
Cloning into '/home/coreboot/coreboot/payloads/external/Memtest86Plus/memtest86plus'...
fatal: unable to access 'https://review.coreboot.org/memtest86plus.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
make[1]: *** [Makefile:17: /home/coreboot/coreboot/payloads/external/Memtest86Plus/memtest86plus] Error 128
make: *** [payloads/external/Makefile.inc:281: payloads/external/Memtest86Plus/memtest86plus/memtest] Error 2
cp: cannot stat 'coreboot/build/coreboot.rom': No such file or directory
sha256sum: apu2_v4.14.0.4.rom: No such file or directory```

**Comment by miczyg1** [comment]
We are aware of the issue and are working on a solution.

**Comment by Strongbyte-SD** [comment]
Thanks @miczyg1, is there a version which does not have this issue ?

**Comment by miczyg1** [comment]
There will be an update to the newer coreboot-sdk and as a result, a newer version of pce-fw-builder will be released, but it is not available currently.

**Comment by Strongbyte-SD** [comment]
Thanks again @miczyg1, Do you know if i can disable Memtest so that i can still build the firmware ? I don't need it for my project.

**Comment by miczyg1** [comment]
As a temporary workaround I have disabled certificate checks of the repositories, so that the errors will not stop the build process: https://github.com/pcengines/pce-fw-builder/tree/cert_workaround
When the build is started from this branch (according to the documentation) no errors will pop-up. If you cloned the pce-fw-builder repository, please execute:
```
cd pce-fw-builder
git fetch
git checkout cert_workaround
./build.sh release v4.14.0.4 apu2
```

Building without memtest is possible. Please execute the following:
```
./build.sh release v4.14.0.4 apu2
# wait until it fails
./build.sh dev-build $PWD/release/coreboot apu2 menuconfig
```

A coreboot configuration menu should pop-up. Go to Payload - > Secondary Payloads and unselect `Load Memtest86+ as a secondary payload`. Save the config file by navigating the buttons on the bottom to select `Save` (use TAB to switch the buttons and press enter when `Save` is highlighted). Ensure the `.config` file is saved as prompted. Then navigate to `Exit` button to leave the configuration menu. Then:

```
./build.sh dev-build $PWD/release/coreboot apu2 CPUS=$(nproc)
```
Now the build will omit Memtest86+ and the result file will be placed in `$PWD/release/coreboot/build/coreboot.rom`

Note that iPXE may have the same problem, so you may need to disable it as well in the Payload submenu.

**Comment by Strongbyte-SD** [comment]
@miczyg1 This worked, thanks for your help.
